export enum Constants {

    SYSTEM_DEFAULT_WORKING_DIRECTORY_VARIABLE = "System.DefaultWorkingDirectory",

    STORAGE_ACCOUNT_NAME_VARIABLE = "STORAGE_ACCOUNT_NAME",
    STORAGE_ACCOUNT_KEY_VARIABLE = "STORAGE_ACCOUNT_KEY",
    STORAGE_ACCOUNT_FILE_SHARE_NAME_VARIABLE = "STORAGE_ACCOUNT_FILE_SHARE_NAME",


    CACHE_MOUNT_PATH_VARIABLE = "CACHE_MOUNT_PATH",
    CACHE_KEY_GLOB_PATTERN_VARIABLE = "CACHE_KEY"
}